# ansible/playbooks/microk8s/control-plane.yml
---
- name: Setup MicroK8s control plane
  hosts: control_plane
  become_user: "{{ ansible_user }}"
  
  tasks:
    - name: Enable MicroK8s addons
      shell: "microk8s enable {{ item }}"
      loop: "{{ microk8s.addons }}"
      register: addon_result
      changed_when: "'is already enabled' not in addon_result.stdout"
      
    - name: Wait for all addons to be ready
      shell: microk8s status --wait-ready
      timeout: 300
      
    - name: Generate join token for workers
      shell: microk8s add-node
      register: join_command
      
    - name: Extract join command
      set_fact:
        microk8s_join_command: "{{ join_command.stdout_lines | select('match', '.*microk8s join.*') | first }}"
        
    - name: Display join command
      debug:
        msg: "Join command: {{ microk8s_join_command }}"
        
    - name: Save join command to file
      copy:
        content: "{{ microk8s_join_command }}"
        dest: "/tmp/microk8s_join_command"
        
    - name: Fetch join command to local machine
      fetch:
        src: "/tmp/microk8s_join_command"
        dest: "/tmp/microk8s_join_command"
        flat: yes