# ansible/playbooks/microk8s/cross-region-workers.yml - Fixed
---
- name: Join cross-region workers using public IP
  hosts: cross_region_workers  # Changed from sweden_workers to cross_region_workers
  become_user: "{{ ansible_user }}"
  
  tasks:
    - name: Get control plane public IP
      set_fact:
        control_plane_public_ip: "{{ hostvars[groups['control_plane'][0]]['ansible_host'] }}"
        
    - name: Check if node is already in cluster
      shell: sg microk8s -c "microk8s kubectl get nodes"
      register: existing_nodes
      failed_when: false
      delegate_to: "{{ groups['control_plane'][0] }}"
      
    - name: Skip if already joined
      debug:
        msg: "Node {{ ansible_hostname }} already in cluster"
      when: ansible_hostname in existing_nodes.stdout
      
    - name: Generate special join command for cross-region worker
      shell: sg microk8s -c "microk8s add-node"
      delegate_to: "{{ groups['control_plane'][0] }}"
      register: cross_region_join_command
      when: ansible_hostname not in existing_nodes.stdout
      
    - name: Extract and modify join command for public IP
      set_fact:
        modified_join_command: "{{ cross_region_join_command.stdout_lines | select('match', '.*microk8s join.*') | first | regex_replace('10\\.0\\.1\\.4', control_plane_public_ip) }}"
      when: ansible_hostname not in existing_nodes.stdout
        
    - name: Display modified join command
      debug:
        msg: "Modified join command: {{ modified_join_command }}"
      when: ansible_hostname not in existing_nodes.stdout
        
    - name: Join cross-region worker using public IP
      shell: "sg microk8s -c '{{ modified_join_command }} --worker'"
      timeout: 300
      register: join_result
      when: ansible_hostname not in existing_nodes.stdout
      
    - name: Display join result
      debug:
        msg: |
          Cross-Region Worker Join Result:
          {{ join_result.stdout | default('Already joined') }}
          
    - name: Wait for node to be ready
      shell: sg microk8s -c "microk8s status --wait-ready"
      timeout: 300