# ansible/playbooks/microk8s/install.yml - UPDATED VERSION
---
- name: Install MicroK8s on all nodes
  hosts: microk8s_cluster
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install snapd
      apt:
        name: snapd
        state: present
        
    - name: Install MicroK8s
      snap:
        name: microk8s
        classic: yes
        channel: "{{ microk8s.channel }}"
        state: present
        
    - name: Add user to microk8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes
        
    - name: Create .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'
        
    - name: Set ownership of .kube directory
      file:
        path: "/home/{{ ansible_user }}/.kube"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
        
    - name: Reset SSH connection to pickup group changes
      meta: reset_connection
        
    - name: Wait for MicroK8s to be ready (using sg to switch groups)
      shell: sg microk8s -c "microk8s status --wait-ready"
      become_user: "{{ ansible_user }}"
      timeout: 300
      
    - name: Create kubectl alias
      lineinfile:
        path: "/home/{{ ansible_user }}/.bashrc"
        line: 'alias kubectl="microk8s kubectl"'
        create: yes