# ansible/playbooks/microk8s/startup-fix.yml
---
- name: Fix MicroK8s startup after reboot
  hosts: microk8s_cluster
  become: yes
  
  tasks:
    - name: Check snap services status
      shell: snap services microk8s
      register: snap_status
      
    - name: Display snap status
      debug:
        msg: "{{ snap_status.stdout }}"
        
    - name: Start MicroK8s snap services
      shell: snap start microk8s
      
    - name: Wait for MicroK8s to initialize
      pause:
        seconds: 30
        
    - name: Enable MicroK8s services
      shell: snap enable microk8s
      
    - name: Restart MicroK8s to ensure clean state
      shell: snap restart microk8s
      
    - name: Wait for restart to complete
      pause:
        seconds: 60

- name: Test MicroK8s functionality
  hosts: microk8s_cluster
  become_user: "{{ ansible_user }}"
  
  tasks:
    - name: Wait for MicroK8s to be ready
      shell: microk8s status --wait-ready
      timeout: 300
      
    - name: Display MicroK8s status
      shell: microk8s status
      register: microk8s_status
      
    - name: Show status
      debug:
        msg: "{{ microk8s_status.stdout }}"