apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: simpleeshop
  labels:
    app: prometheus
    tier: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'simpleeshop'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - simpleeshop
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: simpleeshop
            action: keep
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            regex: http
            action: keep
          - source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_service_name]
            target_label: kubernetes_service_name