apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: simpleeshop
  labels:
    app: prometheus
    tier: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
spec:
  selector:
    app: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  type: ClusterIP