apiVersion: v1
kind: ConfigMap
metadata:
  name: simpleeshop-config
  namespace: simpleeshop
  labels:
    app: simpleeshop
data:
  DB_HOST: "postgres-service"
  DB_USER: "techhub"
  DB_NAME: "techgearhub"
  NODE_ENV: "production"
  PORT: "3000"
  MINIO_HOST: "minio-service"
  MINIO_PORT: "9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
