apiVersion: v1
kind: ConfigMap
metadata:
  name: simpleeshop-config
  namespace: simpleeshop
  labels:
    app: simpleeshop
data:
  DB_HOST: "postgres-service"
  DB_USER: "techhub"
  DB_NAME: "techgearhub"
  NODE_ENV: "production"
  PORT: "3000"
