apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleeshop
  namespace: simpleeshop
  labels:
    app: simpleeshop
    tier: frontend
spec:
  replicas: 3  # Increased to 3 replicas
  selector:
    matchLabels:
      app: simpleeshop
  template:
    metadata:
      labels:
        app: simpleeshop
        tier: frontend
    spec:
      containers:
      - name: simpleeshop
        image: niroth36/simpleeshop:150
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: simpleeshop-config
        env:
        - name: DB_PASSWORD
          value: "!@#123Abc"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - simpleeshop
              topologyKey: kubernetes.io/hostname
