apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleeshop
  namespace: simpleeshop
  labels:
    app: simpleeshop
    tier: frontend
spec:
  replicas: 2  # Single replica to fix session persistence
  selector:
    matchLabels:
      app: simpleeshop
  template:
    metadata:
      labels:
        app: simpleeshop
        tier: frontend
    spec:
      containers:
      - name: simpleeshop
        image: niroth36/simpleeshop:latest  # Your specific image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: simpleeshop-config
        env:
        - name: DB_PASSWORD
          value: "!@#123Abc"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - simpleeshop
            topologyKey: kubernetes.io/hostname