apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  labels:
    app: database
spec:
  project: default
  source:
    repoURL: https://github.com/Niroth36/SimpleEshop-gitops.git
    targetRevision: main
    path: kubernetes/database
  destination:
    server: https://kubernetes.default.svc
    namespace: simpleeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10