apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  labels:
    app: logging
  annotations:
    description: "Deploys Loki and Promtail for centralized logging"
spec:
  project: default
  source:
    repoURL: https://github.com/Niroth36/SimpleEshop.git
    targetRevision: master
    path: kubernetes/loki
  destination:
    server: https://kubernetes.default.svc
    namespace: simpleeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      propagationPolicy: Background
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
