apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  labels:
    app: monitoring
  annotations:
    description: "Deploys Prometheus and Grafana for monitoring"
spec:
  project: default
  source:
    repoURL: https://github.com/Niroth36/SimpleEshop.git
    targetRevision: master
    path: kubernetes/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: simpleeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      propagationPolicy: Background
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 1
