apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simpleeshop
  namespace: argocd
  labels:
    app: simpleeshop
  annotations:
    description: "Deploys the SimpleEshop web application"
spec:
  project: default
  source:
    repoURL: https://github.com/Niroth36/SimpleEshop.git
    targetRevision: master
    path: applications/simpleeshop
  destination:
    server: https://kubernetes.default.svc
    namespace: simpleeshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 10
