# ansible/inventories/azure/hosts.yml - Updated for multi-region
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/azure_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3
    ansible_connection_timeout: 30
    ansible_command_timeout: 300
    
  children:
    microk8s_cluster:
      children:
        control_plane:
          hosts:
            control-plane:
              ansible_host: 108.142.156.228
              private_ip: 10.0.1.4
              microk8s_role: primary
              region: west_europe
              
        workers:
          children:
            west_europe_workers:
              hosts:
                worker-1:
                  ansible_host: 128.251.152.53
                  private_ip: 10.0.2.4
                  microk8s_role: worker
                  region: west_europe
                  
            sweden_workers:
              hosts:
                sweden-worker:
                  ansible_host: 4.223.108.114
                  private_ip: 10.1.2.4
                  microk8s_role: worker
                  region: sweden_central