# ansible/inventories/azure/hosts.yml
all:
  vars:
    ansible_user: azureuser
    ansible_ssh_private_key_file: ~/.ssh/azure_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    microk8s_cluster:
      children:
        control_plane:
          hosts:
            control-plane:
              ansible_host: 172.201.62.186
              private_ip: 10.0.1.4
              microk8s_role: primary
              
        workers:
          hosts:
            worker-1:
              ansible_host: 98.71.182.41
              private_ip: 10.0.2.4
              microk8s_role: worker
              
            worker-2:
              ansible_host: 172.211.23.29
              private_ip: 10.0.2.5
              microk8s_role: worker