apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: simpleeshop
  labels:
    app: minio
    tier: storage
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
    name: api
    protocol: TCP
  - port: 9001
    targetPort: 9001
    name: console
    protocol: TCP
    nodePort: 30901
  type: NodePort
