apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: simpleeshop
  labels:
    app: minio
    tier: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        tier: storage
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        env:
        - name: MINIO_ROOT_USER
          value: "minioadmin"
        - name: MINIO_ROOT_PASSWORD
          value: "minioadmin"
        - name: MINIO_NOTIFY_WEBHOOK_ENABLE_welcome
          value: "on"
        - name: MINIO_NOTIFY_WEBHOOK_ENDPOINT_welcome
          value: "http://welcome-email:8080"
        - name: MINIO_NOTIFY_WEBHOOK_ENABLE_order
          value: "on"
        - name: MINIO_NOTIFY_WEBHOOK_ENDPOINT_order
          value: "http://order-confirmation-email:8081"
        - name: MINIO_NOTIFY_WEBHOOK_QUEUE_LIMIT
          value: "100"
        - name: MINIO_NOTIFY_WEBHOOK_QUEUE_DIR
          value: "/data/.notify-webhook"
        # Configure bucket event subscriptions
        - name: MINIO_NOTIFY_WEBHOOK_BUCKET_welcome
          value: "user-registrations"
        - name: MINIO_NOTIFY_WEBHOOK_BUCKET_order
          value: "order-confirmations"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        volumeMounts:
        - name: minio-data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
