apiVersion: v1
kind: Service
metadata:
  name: mailpit-service
  namespace: simpleeshop
  labels:
    app: mailpit
    tier: backend
spec:
  selector:
    app: mailpit
  ports:
  - port: 1025
    targetPort: 1025
    name: smtp
    protocol: TCP
  - port: 8025
    targetPort: 8025
    name: webui
    protocol: TCP
  type: ClusterIP