apiVersion: v1
kind: Service
metadata:
  name: order-confirmation-email-service
  namespace: simpleeshop
  labels:
    app: order-confirmation-email
    tier: backend
spec:
  selector:
    app: order-confirmation-email
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP