apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-confirmation-email
  namespace: simpleeshop
  labels:
    app: order-confirmation-email
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-confirmation-email
  template:
    metadata:
      labels:
        app: order-confirmation-email
        tier: backend
    spec:
      containers:
      - name: order-confirmation-email
        image: bitnami/node:18
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /app
          cd /app
          echo '{"name":"order-confirmation-email","version":"1.0.0","main":"index.js","dependencies":{"nodemailer":"^6.9.1","minio":"^7.0.32"}}' > package.json
          npm install
          echo 'const http = require("http"); const server = http.createServer((req, res) => { res.writeHead(200, {"Content-Type": "text/plain"}); res.end("Order Confirmation Email Service is running"); }); server.listen(8081, () => { console.log("Order Confirmation Email Service listening on port 8081"); });' > index.js
          node index.js
        envFrom:
        - configMapRef:
            name: order-confirmation-email-config
        ports:
        - containerPort: 8081
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 15
