apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-email
  namespace: simpleeshop
  labels:
    app: welcome-email
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-email
  template:
    metadata:
      labels:
        app: welcome-email
        tier: backend
    spec:
      containers:
      - name: welcome-email
        image: bitnami/node:18
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /app
          cd /app
          echo '{"name":"welcome-email","version":"1.0.0","main":"index.js","dependencies":{"nodemailer":"^6.9.1","minio":"^7.0.32"}}' > package.json
          npm install

          # Create circuit-breaker.js
          cat > /app/circuit-breaker.js << 'EOF'
          class CircuitBreaker {
            constructor(action, options = {}) {
              this.action = action;
              this.failureThreshold = options.failureThreshold || 3;
              this.resetTimeout = options.resetTimeout || 30000; // 30 seconds
              this.state = 'CLOSED';
              this.failureCount = 0;
              this.nextAttempt = Date.now();
              this.name = options.name || 'CircuitBreaker';
            }

            async fire(args) {
              if (this.state === 'OPEN') {
                if (this.nextAttempt <= Date.now()) {
                  this.state = 'HALF-OPEN';
                  console.log(`${this.name}: Circuit half-open, attempting reset`);
                } else {
                  throw new Error(`${this.name}: Circuit is open, failing fast`);
                }
              }

              try {
                const result = await this.action(args);
                this.success();
                return result;
              } catch (error) {
                this.failure();
                throw error;
              }
            }

            success() {
              this.failureCount = 0;
              this.state = 'CLOSED';
              console.log(`${this.name}: Circuit closed after successful operation`);
            }

            failure() {
              this.failureCount++;
              console.log(`${this.name}: Failure count: ${this.failureCount}/${this.failureThreshold}`);

              if (this.failureCount >= this.failureThreshold || this.state === 'HALF-OPEN') {
                this.state = 'OPEN';
                this.nextAttempt = Date.now() + this.resetTimeout;
                console.log(`${this.name}: Circuit opened, will try again at ${new Date(this.nextAttempt).toISOString()}`);
              }
            }

            getStatus() {
              return {
                state: this.state,
                failureCount: this.failureCount,
                nextAttempt: this.state === 'OPEN' ? new Date(this.nextAttempt).toISOString() : null
              };
            }
          }

          module.exports = CircuitBreaker;
          EOF

          # Create handler.js
          cat > /app/handler.js << 'EOF'
          const nodemailer = require('nodemailer');
          const CircuitBreaker = require('./circuit-breaker');

          module.exports = async (event, context) => {
              console.log("Function started with event:", event.body);

              let body;
              try {
                  // Parse the event body if it's a string
                  body = typeof event.body === 'string' ? JSON.parse(event.body) : event.body;
              } catch (error) {
                  console.error("Error parsing event body:", error);
                  return {
                      statusCode: 400,
                      body: JSON.stringify({ error: "Invalid JSON in request body" })
                  };
              }

              // Extract user data from the event
              const userData = body.userData || {};
              const { username, email } = userData;

              if (!email) {
                  console.error("No email address provided");
                  return {
                      statusCode: 400,
                      body: JSON.stringify({ error: "No email address provided" })
                  };
              }

              // Configure SMTP transport
              const smtpHost = process.env.SMTP_HOST || 'mailpit-service';
              const smtpPort = parseInt(process.env.SMTP_PORT || '1025');
              console.log(`Using SMTP server: ${smtpHost}:${smtpPort}`);

              // Create a nodemailer transporter
              const transporter = nodemailer.createTransport({
                  host: smtpHost,
                  port: smtpPort,
                  secure: false, // true for 465, false for other ports
                  tls: {
                      rejectUnauthorized: false // Accept self-signed certificates
                  }
              });

              // Prepare email content
              const mailOptions = {
                  from: '"SimpleEshop" <noreply@simpleeshop.com>',
                  to: email,
                  subject: `Welcome to SimpleEshop, ${username || 'New User'}!`,
                  text: `Hello ${username || 'there'},\n\nWelcome to SimpleEshop! We're excited to have you on board.\n\nHappy shopping!\nThe SimpleEshop Team`,
                  html: `
                      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                          <h2>Welcome to SimpleEshop!</h2>
                          <p>Hello ${username || 'there'},</p>
                          <p>We're excited to have you join our community of tech enthusiasts!</p>
                          <p>With your new account, you can:</p>
                          <ul>
                              <li>Browse our extensive catalog of tech products</li>
                              <li>Save items to your wishlist</li>
                              <li>Track your orders</li>
                              <li>Receive exclusive offers</li>
                          </ul>
                          <p>If you have any questions, feel free to contact our support team.</p>
                          <p>Happy shopping!</p>
                          <p><strong>The SimpleEshop Team</strong></p>
                      </div>
                  `
              };

              // Create a circuit breaker for email sending
              const emailCircuitBreaker = new CircuitBreaker(
                  async (mailOpts) => await transporter.sendMail(mailOpts),
                  {
                      failureThreshold: 3,
                      resetTimeout: 30000, // 30 seconds
                      name: 'WelcomeEmailCircuit'
                  }
              );

              try {
                  // Send the email using the circuit breaker
                  const info = await emailCircuitBreaker.fire(mailOptions);
                  console.log('Email sent successfully:', info.messageId);

                  return {
                      statusCode: 200,
                      body: JSON.stringify({
                          status: 'success',
                          message: 'Welcome email sent successfully',
                          recipient: email,
                          messageId: info.messageId,
                          circuitStatus: emailCircuitBreaker.getStatus()
                      })
                  };
              } catch (error) {
                  console.error('Error sending email:', error);
                  return {
                      statusCode: 500,
                      body: JSON.stringify({
                          error: 'Failed to send welcome email',
                          details: error.message,
                          circuitStatus: emailCircuitBreaker.getStatus()
                      })
                  };
              }
          };
          EOF

          # Create index.js that uses the handler
          cat > /app/index.js << 'EOF'
          const http = require('http');
          const handler = require('./handler');

          const server = http.createServer(async (req, res) => {
              if (req.method === 'GET' && req.url === '/') {
                  res.writeHead(200, {"Content-Type": "text/plain"});
                  res.end("Welcome Email Service is running");
                  return;
              }

              if (req.method === 'POST') {
                  let body = '';
                  req.on('data', chunk => {
                      body += chunk.toString();
                  });

                  req.on('end', async () => {
                      try {
                          const result = await handler({ body }, {});
                          res.writeHead(result.statusCode, {"Content-Type": "application/json"});
                          res.end(result.body);
                      } catch (error) {
                          console.error('Error handling request:', error);
                          res.writeHead(500, {"Content-Type": "application/json"});
                          res.end(JSON.stringify({ error: 'Internal server error' }));
                      }
                  });
                  return;
              }

              res.writeHead(404, {"Content-Type": "text/plain"});
              res.end("Not Found");
          });

          const PORT = process.env.PORT || 8080;
          server.listen(PORT, () => {
              console.log(`Welcome Email Service listening on port ${PORT}`);
          });
          EOF

          node index.js
        envFrom:
        - configMapRef:
            name: welcome-email-config
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15
