apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-email
  namespace: simpleeshop
  labels:
    app: welcome-email
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-email
  template:
    metadata:
      labels:
        app: welcome-email
        tier: backend
    spec:
      containers:
      - name: welcome-email
        image: niroth36/welcome-email:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: welcome-email-config
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 15