apiVersion: v1
kind: Service
metadata:
  name: welcome-email-service
  namespace: simpleeshop
  labels:
    app: welcome-email
    tier: backend
spec:
  selector:
    app: welcome-email
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP