apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: simpleeshop
  labels:
    app: grafana
    tier: monitoring
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        access: proxy
        isDefault: true
        editable: true
        version: 1
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy
        isDefault: false
        editable: true
        version: 1
