apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
  namespace: simpleeshop
  labels:
    app: prometheus-adapter
    tier: monitoring
spec:
  selector:
    app: prometheus-adapter
  ports:
  - port: 443
    targetPort: 6443
    name: https
    protocol: TCP
  type: ClusterIP